# Generated by Django 6.0.3 on 2026-05-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_tutor_user_alter_tutor_qualification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tutor',
            name='total_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
