# Generated by Django 6.0.3 on 2026-05-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0003_tutor_avg_rating_tutor_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
